name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: GitLab project sync
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://gitlab.com/raksit_m/learn-aws-s3-lambda-elasticache.git
          target-username: raksit_m
          target-token: ${{ secrets.TARGET_TOKEN }}
