image: node:18-alpine

stages:
  - build
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install -g serverless
    - npm install

deploy_to_aws:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  needs:
    - install_dependencies
  script:
    - npm install -g serverless
    - sls deploy --stage prod

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/